name: Automationchetan_localcommit_scala
description: test random description
version: 0.0.1
author: abhisheks+e2etests@prophecy.io
language: scala
buildSystem: ''
buildSystemDetails:
  artefactID: automationchetanlocalcommitscala
  parentArtefactID: abhishekse2etestsprophecyioteam
  buildSystem: maven
  author: null
  createdAt: '2025-09-03 06:58:22'
pipelines:
  pipelines/Automationchetan_localcommit_scala_Pipeline:
    name: Automationchetan_localcommit_scala_Pipeline
    description: automation workflow
    author: abhisheks+e2etests@prophecy.io
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2025-09-03 07:00:57'
    datasets:
      inputs:
      - datasets/test_dataset
      outputs: []
    subgraphs: []
    dependencies: {}
datasets:
  datasets/test_dataset:
    name: test_dataset
    description: ''
    author: abhisheks+e2etests@prophecy.io
    createdAt: '2025-09-03 07:09:11'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 3
        datasetType: File
        description: ''
        author: abhisheks+e2etests@prophecy.io
        createdAt: '2025-09-03 07:09:11'
templates: {}
jobs: {}
gemContainer:
  languageVersion: 2.12.15
  gemLibsVersion: 1.1.26
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2025-09-03 06:58:22'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2025-09-03T06:59:15.935Z'
  name: ProphecyLibsScala
  version: 8.13.0-SNAPSHOT
  createdAt: '2025-09-03T06:58:22.750458Z'
  type: plibMaven
  enabled: true
  entity: Project
  description: Default dependency for Prophecy Libs
  scope: Project
  exclusions: []
  editable: true
projectDependencies:
  '29':
    projectUID: 29
    projectName: scala_project
    repositoryPath: gitUri=http://gitserver:3000/QWR30Rk3_team_5/j49hpERj_project_29.git&subPath=
    version: scala_project/v1
    isDefault: false
    author: null
    createdAt: '2025-09-03 06:57:54'
  '2':
    projectUID: 2
    projectName: ProphecyWarehouseScala
    repositoryPath: gitUri=http://gitserver:3000/aTbIAI3r_team_2/aTbIAI3r_project_2.git&subPath=
    version: 0.0.6
    isDefault: true
    author: null
    createdAt: '2025-09-03 06:57:54'
  '1':
    projectUID: 1
    projectName: ProphecySparkBasicsScala
    repositoryPath: gitUri=http://gitserver:3000/aTbIAI3r_team_2/aTbIAI3r_project_1.git&subPath=
    version: 0.2.6.3
    isDefault: true
    author: null
    createdAt: '2025-09-03 06:57:54'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
projectConfigurations: {}
